# Generated by Django 4.2.27 on 2026-02-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='provider',
            field=models.CharField(default='Sociodynamics AI', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
